// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD84WpTQjKF5fQ6DS8kWY4E9IMTZGJ6AQ',
    appId: '1:1087565649986:web:3cfaa44322d269a0f735db',
    messagingSenderId: '1087565649986',
    projectId: 'vendor-app-c426a',
    authDomain: 'vendor-app-c426a.firebaseapp.com',
    storageBucket: 'vendor-app-c426a.firebasestorage.app',
    measurementId: 'G-K6ZSTE0B8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdbTKPOHqWM9kLpPc7Cddmu5IzoIhLE20',
    appId: '1:1087565649986:android:8dc507473ed8a279f735db',
    messagingSenderId: '1087565649986',
    projectId: 'vendor-app-c426a',
    storageBucket: 'vendor-app-c426a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNDDGb1NRFA8Cf7NYV0eAVKuPIBGkS5OI',
    appId: '1:1087565649986:ios:5ad1710ba653909cf735db',
    messagingSenderId: '1087565649986',
    projectId: 'vendor-app-c426a',
    storageBucket: 'vendor-app-c426a.firebasestorage.app',
    iosBundleId: 'com.ihaan.vendorapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNDDGb1NRFA8Cf7NYV0eAVKuPIBGkS5OI',
    appId: '1:1087565649986:ios:15b2173795c098e5f735db',
    messagingSenderId: '1087565649986',
    projectId: 'vendor-app-c426a',
    storageBucket: 'vendor-app-c426a.firebasestorage.app',
    iosBundleId: 'com.example.vendorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD84WpTQjKF5fQ6DS8kWY4E9IMTZGJ6AQ',
    appId: '1:1087565649986:web:e237689d2f198c56f735db',
    messagingSenderId: '1087565649986',
    projectId: 'vendor-app-c426a',
    authDomain: 'vendor-app-c426a.firebaseapp.com',
    storageBucket: 'vendor-app-c426a.firebasestorage.app',
    measurementId: 'G-1Y80R4MG83',
  );
}
